name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-devops .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-devops

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/hello-devops
            docker stop app || true
            docker rm app || true
            docker run -d -p 8085:80 --name app ${{ secrets.DOCKER_USERNAME }}/hello-devops