- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.VM_HOST }}
    username: ${{ secrets.VM_USER }}
    key: ${{ secrets.VM_SSH_KEY }}
    script: |
      docker pull ${{ secrets.DOCKER_USERNAME }}/hello-devops:latest
      docker stop app || true
      docker rm app || true
      docker run -d -p 8085:80 --name app ${{ secrets.DOCKER_USERNAME }}/hello-devops:latest